### ISSUE TITLE
Enable both versioned symbols

### ISSUE THREAD

**Issue by RDunkley** [RDunkley/meta-dotnet-core#1]
The modified curl version uses CURL_OPENSSL_3 for the versioned symbols. Recommend adding both CURL_OPENSSL_3 and CURL_OPENSSL_4 to prevent breaking other libraries that may depend on CURL_OPENSSL_4.

**Comment by Tragetaschen** [comment]
The curl dependency will be removed in 5.0: https://github.com/dotnet/runtime/issues/28891#issuecomment-539705582

**Comment by RDunkley** [comment]
Added support for 5.0 in 3c92d36fd3d4dc2ac8b25da7cbb7bcaed4f713a9. I confirmed their binaries do remove the dependency for curl. I still need to update the bbappend to only target 2.x and 3.x.

**Comment by RDunkley** [comment]
I dropped the 2.x and 3.x versions from master, so I also dropped the curl bbappend.
