### ISSUE TITLE
Mono dependencies

### ISSUE THREAD

**Issue by td28354** [RDunkley/meta-dotnet-core#17]
Hi,

I'm trying to install .net core using the meta-dotnet-core using the sumo branch but i get some QA Issues:

ERROR: dotnet-core-3.0.0-r0 do_package_qa: QA Issue: /usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.dll contained in package dotnet-core requires mono(System.CodeDom), but no providers found in RDEPENDS_dotnet-core? [file-rdeps]

ERROR: dotnet-core-3.0.0-r0 do_package_qa: QA Issue: /usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/System.dll contained in package dotnet-core requires mono(System.IO.Ports), but no providers found in RDEPENDS_dotnet-core? [file-rdeps]

ERROR: dotnet-core-3.0.0-r0 do_package_qa: QA Issue: /usr/share/dotnet/shared/Microsoft.NETCore.App/3.0.0/WindowsBase.dll contained in package dotnet-core requires mono(System.IO.Packaging), but no providers found in RDEPENDS_dotnet-core? [file-rdeps]

Can you help me to fix the issue.

Thanks

**Comment by RDunkley** [comment]
I just built sumo for the microzed board and didn't have any issues. What board are you building for?

**Comment by Tragetaschen** [comment]
My psychic powers tell me that @td28354's build host has mono installed and @RDunkley's hasn't.
http://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=51baa9a3b4948683a962674b4854ceaa06d3eb4f

Depending on whether the host provides `monodis`, file-rdeps' `rpmdeps` dependency would scan the *.dll and determine that mono is a necessary dependency. The above commit disables that starting with Yocto Zeus.

A quick fix would be a .bbappend with
```
SKIP_FILEDEPS = "1"
```
