### ISSUE TITLE
Consider using INSANE_SKIP="staticdev" instead of RDEPENDS=-staticdev

### ISSUE THREAD

**Issue by Tragetaschen** [RDunkley/meta-dotnet-core#18]
I have noticed on my image that using aspnet-core or dotnet-core would pull in a lot of -dev dependencies and a python3 interpreter amongst other things. I was able to trace those back to the RDEPENDS="aspnet-core-staticdev" dependency.

With a .bbappend containing
```
FILES_${PN}-staticdev_remove = "${datadir}/dotnet/shared/Microsoft.NETCore.App/${PV}/*.a"
RDEPENDS_${PN}_remove = "aspnet-core-staticdev"
INSANE_SKIP_${PN} += "staticdev"
```
the *.a files are provided through the main package. Since that would normally trigger a QA error, it is suppressed with the INSANE_SKIP.

The *.a files are an integral part of the .NET Core installation and not meant for development in the bitbake sense, so this seems like the better approach.

**Comment by RDunkley** [comment]
Thanks for the fix. I didn't realize it was adding so many additional files.
