### ISSUE TITLE
getting to bake under zeus?

### ISSUE THREAD

**Issue by tbandtg** [RDunkley/meta-dotnet-core#20]
I edited the bb to include zeus, 

But I get an RDEPENDS on libcurl.so.4 64 bit Is there any way to get past this?

Is there a way to get this to work?

**Comment by RDunkley** [comment]
I haven't used Zeus at all, but I just added support for .Net Core 5 in commit 3c92d36fd3d4dc2ac8b25da7cbb7bcaed4f713a9 which removes the dependency for libcurl. You might try that.

**Comment by indyIOT** [comment]
I did thanks, I was able to get it to bake. Then the .net developers really didn't want to update their vs installs. So I ended up manually installing dotnet core 3.1 from the command line. But when 5 is officially released next month we will probably move then. 

Thanks for the help!!
