### ISSUE TITLE
Support for ASP.NET Core 3.1.x (thud)

### ISSUE THREAD

**Issue by bcraun** [RDunkley/meta-dotnet-core#22]
I need to add support for ASP.NET Core 3.1.8 and I believe I understand the process for copying and updating the 3.0.0 files to add support for 3.1.8. 

One specific question I have is related to the following:

```
SRC_URI = "https://download.visualstudio.microsoft.com/download/pr/b0c44e05-b7a1-4221-94ec-a0c0d3a11eed/afc61567dd6db8f097e244871889458c/aspnetcore-runtime-3.0.0-linux-x64.tar.gz;subdir=aspnet-${PV}"

SRC_URI[md5sum] = "953d1fcef81eba738ccf30589563ec59"
SRC_URI[sha256sum] = "8d28aa53f47e8b2ef5c39ddee75cc22527ace332c528bbe85da99bf1b4906b36"
```

I know the value of the `SRC_URI` to use, but am not sure from where the `SRC_URI[md5sum]` and `SRC_URI[sha256sum]` were derived. They are not published on Microsoft's download page so I'm assuming that they were calculated by the author? Is there a way to disable the checksum validation or is this required by bitbake? Any advice is much appreciated?

Thanks,
Bill

**Comment by bcraun** [comment]
Found the answer

**Comment by RDunkley** [comment]
By the way, the Master branch has 3.1.8 already in it (as well as 5.0.0 RC1). I haven't pushed it to the thud branch yet.

**Comment by bcraun** [comment]
Thanks, I was able to add it in my thud branch.
