### ISSUE TITLE
ASP.NET application recipe example

### ISSUE THREAD

**Issue by antaveiv** [RDunkley/meta-dotnet-core#27]
I have successfully installed .NET 5 into my image. Is there an example of a recipe for deploying an ASP.NET application somewhere?
Thanks

**Comment by RDunkley** [comment]
I don't have an example for this. If you find one or create one, I can point to it from the README.

**Comment by shyd** [comment]
Hi @antaveiv 
did you manage to build your app from sources with a recipe? Deploying an prebuilt dll seems obvious, but I want to build it with bitbake instead.

Cheers
