### ISSUE TITLE
Failed to attach to process when Remote Debugging (vsdbg 2022)

### ISSUE THREAD

**Issue by TGibsonReach** [RDunkley/meta-dotnet-core#39]
Updated to vsdbg 2022 using pagdots (@pagdot) forked [branch](https://github.com/pagdot/meta-dotnet-core). 
Currently side loading a basic .Net6 console app to validate the remote debugger and running into an issue where the remote debugger fails to process the attach request because it cannot find the file specified. 

This only happens when trying to remote debug from Visual Studio 2022. We can remote debug the .Net6 Application from Visual Studio 2019, however 2019 doesn't support .Net6 Development...

Cross Platform Log 
![image](https://user-images.githubusercontent.com/100977766/165185829-a3648a92-c73c-4903-be7f-9f9386decf71.png)

Visual Studio Pop Up 
![image](https://user-images.githubusercontent.com/100977766/165186114-41a1f348-aae7-4334-aafa-f890ac62e3a5.png)

We're not entirely sure which file it is looking for? Has anyone else experienced this issue?

**Comment by TGibsonReach** [comment]
Update* 
Comparing vs2022 and vs2019 folders found in .vs-debugger/ we found the vs2022 folder was missing the `default.vsdbg-config.json` file. 

We added the below line to `vsdbg_17.x.inc`  to explicitly copy over the file which fixed our problem :
```
do_install_prepend () {
 	install -d ${D}${ROOT_HOME}/.vs-debugger/vs2022/
+	install -m 0755 ${S}/default.vsdbg-config.json ${D}${ROOT_HOME}/.vs-debugger/vs2022/
 	install -m 0755 ${S}/vsdbg ${D}${ROOT_HOME}/.vs-debugger/vs2022/
 	install -m 0644 ${S}/license.txt ${D}${ROOT_HOME}/.vs-debugger/vs2022/
 	install -m 0644 ${S}/ThirdPartyNotices.txt ${D}${ROOT_HOME}/.vs-debugger/vs2022/

```

**Comment by mischo5500** [comment]
Would be nice to merge it into master, got the same problem, when trying launch and debug application under .NET 6.0 and vs2022 vsdbg @RDunkley .

**Comment by RDunkley** [comment]
This should be in Master now.
