### ISSUE TITLE
dotnet 6.0 runtime works but compiled software does not

### ISSUE THREAD

**Issue by simonetolotti** [RDunkley/meta-dotnet-core#46]
The Runtime works in my target

![image](https://user-images.githubusercontent.com/20853864/200612915-04ef6a96-474e-469f-a8a7-d29c02f67377.png)

this is my target (Arm 7 - 32 bit)
![image](https://user-images.githubusercontent.com/20853864/200613387-ad29df74-3c97-40ca-8b9f-b4470876ccd7.png)

I created a very simple console application for test
![image](https://user-images.githubusercontent.com/20853864/200613729-abf76fc2-a67d-4287-9576-560a980f49b4.png)

I published with the following options:
![image](https://user-images.githubusercontent.com/20853864/200614395-535a6352-b22a-42a2-9ad4-1b76c5e670a2.png)

but when I try:
![image](https://user-images.githubusercontent.com/20853864/200614747-534eb99f-8ad8-43f6-a5a7-bc8fe36e1a9b.png)

Anyway I have tried different configurations without positive effect. Could you help me ?

**Comment by dunkleyr** [comment]
Not sure on this, might have something to do with this:

https://github.com/dotnet/runtime/issues/33727

It looks like the fix is in v6.0.0, but you might want to try a later version of the runtime and compiler.
